---
title: "Knoblich_modules"
output: html_document
date: "2023-11-20"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r Read in the Knoblich data}

Modules<-readRDS("CHOOSE_ASD_Modules.rds?download=1") #  27783 28344 (Genes x Columns)

```

## Mapping to Knoblich reference data 

```{r }

## 1) Converting query data to single cell experiment
seurat_integrated<-readRDS("../files/scSeq_PA/analysis/seurat_integrated.rds") # Read the scRNA data
scRNA.sce <- as.SingleCellExperiment(seurat_integrated)

Knoblich_reference <- Modules

Knoblich_reference <- subset(Knoblich_reference, cells = WhichCells(Knoblich_reference, downsample = 200))

Idents(Knoblich_reference) <- Knoblich_reference$celltype_cl_coarse

Knoblich_reference <- SCTransform(Knoblich_reference, ncells = 3000, verbose = FALSE, method = "poisson") %>%
  RunPCA(verbose = FALSE) %>%
  RunUMAP(dims = 1:30)



AR<- as.SingleCellExperiment(Knoblich_reference)
pred.hneurons<-SingleR(test = scRNA.sce,ref = AR,labels = AR$celltype_cl_coarse)


cdata = cbind(colData(scRNA.sce), 
              data.frame(HumanNeurons.label = pred.hneurons$pruned.labels))

rescounts = table(pred.hneurons$pruned.labels, useNA="ifany")
othercells = names(rescounts)[rescounts<100]

cdata$Neurons100.label = pred.hneurons$pruned.labels
cdata$Neurons100.label[cdata$Neurons100.label %in%othercells] = "other"

Neuronpalette = colorRampPalette(brewer.pal(16, "Paired"))(length(unique(cdata$Neurons100.label)))
names(Neuronpalette) = unique(cdata$Neurons100.label)
Neuronpalette["other"] = "gray30"

colData(scRNA.sce) = cdata

# Adding reduced dims to the seurat converted object

umap<-Embeddings(seurat_integrated,"umap")[,]
reducedDim(scRNA.sce, "UMAP")<-umap

pca<-Embeddings(seurat_integrated,"pca")[,]
reducedDim(scRNA.sce, "PCA")<-pca

tsne<-Embeddings(seurat_integrated,"tsne")[,]
reducedDim(scRNA.sce, "TSNE")<-tsne


colData(scRNA.sce)$UMAP1<-data.frame(reducedDim(scRNA.sce)[,1])
colData(scRNA.sce)$UMAP2<-data.frame(reducedDim(scRNA.sce)[,2])

scRNA.sce$UMAP1<-as.numeric(scRNA.sce$UMAP1$reducedDim.scRNA.sce....1.)
scRNA.sce$UMAP2<-as.numeric(scRNA.sce$UMAP2$reducedDim.scRNA.sce....2.)

pdf("Heatmap_knoblich.pdf")
plotScoreHeatmap(pred.hneurons)
dev.off()
colsname<-unname(alphabet())[1:30]

pdf("plot_knoblich.pdf")
cowplot::plot_grid(
  scater::plotReducedDim(scRNA.sce, 'UMAP', colour_by = 'Neurons100.label') 
  + scale_fill_manual(values=colsname, aesthetics="colour", name="Celltype"),
  scater::plotReducedDim(scRNA.sce, 'UMAP', colour_by = 'seurat_clusters', text_by = 'seurat_clusters')
  + scale_fill_manual(values=colsname,aesthetics="colour",  name="Clusters"))
dev.off()



pdf("plot_knoblich_sc.pdf")
gg<-cowplot::plot_grid(
  scater::plotReducedDim(scRNA.sce, 'UMAP', colour_by = 'Neurons100.label'))
gg  + scale_fill_manual(values=colsname, aesthetics="colour", name="Celltype")
dev.off()

```

