---
title: "Snippets"
output: html_document
date: "2023-12-08"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


#map to allen brain atlas
```{r, load data for Prediction, include = FALSE,warning=FALSE}

## 1) Converting query data to single cell experiment
scRNA.sce <- as.SingleCellExperiment(seurat_integrated)

allen_reference <- readRDS("")

allen_reference <- subset(allen_reference, cells = WhichCells(allen_reference, downsample = 200))



Idents(allen_reference) <- allen_reference$subclass_label

allen_reference <- SCTransform(allen_reference, ncells = 3000, verbose = FALSE, method = "poisson") %>%
  RunPCA(verbose = FALSE) %>%
  RunUMAP(dims = 1:30)



AR<- as.SingleCellExperiment(allen_reference)
pred.hneurons<-SingleR(test = scRNA.sce,ref = AR,labels = AR$subclass_label)


cdata = cbind(colData(scRNA.sce), 
              data.frame(HumanNeurons.label = pred.hneurons$pruned.labels))

rescounts = table(pred.hneurons$pruned.labels, useNA="ifany")
othercells = names(rescounts)[rescounts<100]

cdata$Neurons100.label = pred.hneurons$pruned.labels
cdata$Neurons100.label[cdata$Neurons100.label %in%othercells] = "other"

Neuronpalette = colorRampPalette(brewer.pal(16, "Paired"))(length(unique(cdata$Neurons100.label)))
names(Neuronpalette) = unique(cdata$Neurons100.label)
Neuronpalette["other"] = "gray30"

colData(scRNA.sce) = cdata

# Adding reduced dims to the seurat converted object

umap<-Embeddings(seurat_integrated,"umap")[,]
reducedDim(scRNA.sce, "UMAP")<-umap

pca<-Embeddings(seurat_integrated,"pca")[,]
reducedDim(scRNA.sce, "PCA")<-pca

tsne<-Embeddings(seurat_integrated,"tsne")[,]
reducedDim(scRNA.sce, "TSNE")<-tsne


colData(scRNA.sce)$UMAP1<-data.frame(reducedDim(scRNA.sce)[,1])
colData(scRNA.sce)$UMAP2<-data.frame(reducedDim(scRNA.sce)[,2])

scRNA.sce$UMAP1<-as.numeric(scRNA.sce$UMAP1$reducedDim.scRNA.sce....1.)
scRNA.sce$UMAP2<-as.numeric(scRNA.sce$UMAP2$reducedDim.scRNA.sce....2.)


plotScoreHeatmap(pred.hneurons)



#pdf("plot.pdf")
cowplot::plot_grid(
  scater::plotReducedDim(scRNA.sce, 'UMAP', colour_by = 'Neurons100.label') 
  + scale_fill_manual(values=colsname, aesthetics="colour", name="Celltype"),
  scater::plotReducedDim(scRNA.sce, 'UMAP', colour_by = 'seurat_clusters', text_by = 'seurat_clusters')
  + scale_fill_manual(values=colsname,aesthetics="colour",  name="Clusters"))
#dev.off()


```


```{r,fig.cap="Neurons clusters",fig.width=8,fig.height=8}
p<-plotColData(scRNA.sce, x="Neurons100.label", y="type", colour_by="seurat_clusters")+
  scale_fill_manual(values=colsname, aesthetics="colour")
p + guides(color=guide_legend(title="Clusters")) + theme(axis.text.x = element_text(angle=90))
```


```{r,fig.cap="Sample IDs for each seurat clusters",fig.width=8,fig.height=8}
p<-plotColData(scRNA.sce, x="type", y="seurat_clusters", colour_by="Neurons100.label")+
  scale_fill_manual(values=colsname, aesthetics="colour")
p + guides(color=guide_legend(title="Cell Type"))+theme(axis.text.x = element_text(angle=90))
```

## Comparing clusters
```{r Cluster Comparison per Sample, fig.width=8, fig.height=5,warning=FALSE}
#  Prepare a counts matrix with labeled rows and columns. 
# sce <- logcounts(sce)  # access log-transformed counts matrix
# cellLabels <- as.factor(scRNA.sce$HumanPrimaryCellAtlas.label)
# colnames(scRNA.sce) <- cellLabels

#Calculating the percentages of cell per cluster
number_perCluster<- as.data.frame.matrix(table(Samples=scRNA.sce$type, 
                                               Clusters=scRNA.sce$seurat_clusters))
prop_per_Sample<- prop.table(table(Samples=scRNA.sce$type, 
                                   Clusters=scRNA.sce$seurat_clusters), margin = 1)


#Group comparisons
chisqmatrix <- function(x) {
  names = colnames(x);  
  num = length(names)
  m = matrix(nrow=num,ncol=num,dimnames=list(names,names))
  for (i in names) {
    for (j in names) {
      m[i,j] = chisq.test((x[,c(i,j)]))$p.value
    }
  }
  diag(m)=NA
  m[lower.tri(m)]=NA
  colnames(m)=names
  rownames(m)=names
  return (m)
}

mat = chisqmatrix(t(number_perCluster))

cormat = matrix(data = p.adjust(mat, method = "BH"), 
                nrow = nrow(mat), ncol=ncol(mat))
```



```{r,fig.cap="Proportion per sample",fig.width=8,fig.height=8}
pheatmap::pheatmap(prop_per_Sample)

```



###
```{r save}




```
