---
title: "Cluster Identification"
date: "2023-01-12"
output:
  html_document:
    theme: cerulean
    toc: yes
    toc_float:
      collapsed: true
---

# Clustering Analysis


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

```{r Calling libraries, echo=FALSE, include=FALSE}
library(SingleR)
library(ggpubr)
library(SingleCellExperiment)
library(Seurat)
library(ggplot2)
library(scuttle)
library(scater)
library(tidyverse)
library(data.table)
library(RColorBrewer)
library(RCurl)
library(randomcoloR)
library(cowplot)
library(viridis)
library(gprofiler2)
library(pals)
library(reshape2)
library(CATALYST)
library(clustree)
```


```{r load data, include = FALSE}
dir.create("./output/02_Clustering/", showWarnings = F)
seurat_integrated <- readRDS(file="./data/QC_dataClustered.filt.rds")
scRNA.sce <- as.SingleCellExperiment(seurat_integrated)

DefaultAssay(seurat_integrated) <- "RNA"
Idents(seurat_integrated) <- "type"

colsname<-unname(alphabet())[1:36]
SamplePalette =  c("#000000","#3399FF")
```

# Mapping of clusters to reference data sets

## Knoblich Clusters

```{r}
library(scSorter)

knoblichgenelist <- read.table("./data/Knoblich/Knoblich_GeneList.txt", header=T)
knoblichgenelist<- knoblichgenelist[knoblichgenelist$cluster %in% c(1:20), ]
knoblichgenelist$cluster <- paste0("knoblich_",formatC(as.numeric(knoblichgenelist$cluster), width=2, flag = "0"))
colnames(knoblichgenelist) <- c("Type", "Marker")

Idents(seurat_integrated) <- "seurat_clusters"
data= subset(seurat_integrated, downsample = 100)
knoblichtypes <- scSorter(data@assays$RNA@counts, knoblichgenelist)
metadata = data@meta.data 
metadata = metadata[,! colnames(metadata) %in% c("KnoblichPredType")]
data@meta.data <- cbind(metadata, KnoblichPredType = knoblichtypes$Pred_Type)
```


```{r}
p<-DimPlot(data, reduction = "umap", group.by = "KnoblichPredType")
p
ggsave("./output/02_Clustering/Clustering_KnoblichPredTypes.svg",p)
```


```{r}
crosstab=table(KnoblichType = data$KnoblichPredType, Cluster=data$seurat_clusters)

ggplot(as.data.frame(crosstab), aes(fill=KnoblichType, 
                                    x=Cluster, y=Freq)) + geom_bar(position="fill", stat="identity")+theme_classic()
crosstab
chisq.test(crosstab)

```

```{r}
# cleanup 
rm(list=ls()[!ls()%in%c("scRNA.sce", "seurat_integrated", "SamplePalette")])
gc()

```

## Knoblich Map to annotation

```{r, fig.width=10, fig.height=5}

Knoblich_reference<-readRDS("./data/Knoblich/CHOOSE_ASD_Modules.rds")

Idents(Knoblich_reference) <- "celltype_cl_coarse"

Knoblich_reference <- subset(Knoblich_reference, cells = WhichCells(Knoblich_reference, downsample = 200))

AR<- as.SingleCellExperiment(Knoblich_reference)
pred.hneurons<-SingleR(test = scRNA.sce,ref = AR,labels = AR$celltype_cl_coarse)

colnames(pred.hneurons) <- paste0("Knobl.", colnames(pred.hneurons))
seurat_integrated@meta.data <- cbind(seurat_integrated@meta.data, pred.hneurons)

p<- DimPlot(seurat_integrated, group.by = "Knobl.labels", label = T)

p2<- DimPlot(seurat_integrated, group.by = "seurat_clusters", label = T)
p|p2
ggsave("./output/02_Clustering/Clustering_KnoblMapped.svg",p)

table(seurat_integrated$seurat_clusters, seurat_integrated$Knobl.labels)

```


```{r, fig.width=12, fig.height=12}
feats=grep("Knobl.scores", colnames(seurat_integrated@meta.data),value=T)
p<-FeaturePlot(seurat_integrated, features = feats)+NoLegend()
p
ggsave("./output/02_Clustering/Clustering_KnoblScores.svg")
```

```{r}
# cleanup 
rm(list=ls()[!ls()%in%c("scRNA.sce", "seurat_integrated", "SamplePalette")])
gc()

```


## Kanton et al Table 4 Celltypes

```{r}
kantongenelist <- read.table("./data/KantonGeneList/Table4_Kanton.txt", header=T, sep="\t")
colnames(kantongenelist) <- c("Type", "Marker")
data= subset(seurat_integrated, downsample = 100)
kantonT4types <- scSorter(data@assays$RNA@counts, kantongenelist)

metadata = data@meta.data 
metadata = metadata[,! colnames(metadata) %in% c("KantonT4PredType")]
data@meta.data <- cbind(metadata, KantonT4PredType = kantonT4types$Pred_Type)
```


```{r, fig.width=18, fig.height=5}
p<-DimPlot(data, group.by = "KantonT4PredType", split.by = "type")
p
ggsave("./output/02_Clustering/Clustering_KantonT4PredTypes.svg")

p<-DimPlot(data[,data$KantonT4PredType=="choroid plexus"], group.by = "KantonT4PredType", split.by = "type")
p
ggsave("./output/02_Clustering/Clustering_KantonT4PredTypesChoroidOnly.svg")
```


```{r}
crosstab=table(KantonT4Type = data$KantonT4PredType, Cluster=data$seurat_clusters)

ggplot(as.data.frame(crosstab), aes(fill=KantonT4Type, x=Cluster, y=Freq)) + geom_bar(position="fill", stat="identity")+theme_classic()
crosstab
chisq.test(crosstab)

```

## Kanton et al Table 14 Celltypes

```{r}
kantongenelist <- read.table("./data/KantonGeneList/Table14_Kanton.txt", header=T, sep="\t")
colnames(kantongenelist) <- c("Type", "Marker")
data= subset(seurat_integrated, downsample = 100)
kantonT14types <- scSorter(data@assays$RNA@counts, kantongenelist)

metadata = data@meta.data 
metadata = metadata[,! colnames(metadata) %in% c("KantonT14PredType")]
data@meta.data <- cbind(metadata, KantonT14PredType = kantonT14types$Pred_Type)

DimPlot(data, group.by = "KantonT14PredType")

crosstab=table(Kanton14Type = data$KantonT14PredType, Cluster=data$seurat_clusters)

ggplot(as.data.frame(crosstab), aes(fill=Kanton14Type, x=Cluster, y=Freq)) + geom_bar(position="fill", stat="identity")+theme_classic()
crosstab
chisq.test(crosstab)

```

```{r cleanup}
# cleanup 
rm(list=ls()[!ls()%in%c("scRNA.sce", "seurat_integrated", "SamplePalette")])
gc()

```


## HumanDevData Map to annotation

```{r maphumdev, fig.width=6, fig.height=6}
HumDev_reference<-readRDS("./data/HumDev/human_dev_GRCh38-3.0.0_subset_seurat.RDS")

HumDev_reference$development_stage_ontology_term_id %>% table()
HumDev_reference$Tissue%>% table()
HumDev_reference$Subdivision %>% table()
HumDev_reference$Subregion %>% table()
HumDev_reference$dissection %>% table()
HumDev_reference@meta.data %>% dplyr::select("CellClass", "development_stage_ontology_term_id") %>% table()
HumDev_reference@meta.data <- cbind(HumDev_reference@meta.data, humdev_celltype = paste0(HumDev_reference$CellClass,"_", HumDev_reference$development_stage_ontology_term_id))

Idents(HumDev_reference) <- "humdev_celltype"

## remap to Gene Symvols
library(org.Hs.eg.db)
master_gene_table <- mapIds(org.Hs.eg.db, keys = rownames(HumDev_reference), keytype = "ENSEMBL", column="SYMBOL")
master_gene_table <- as.data.frame(master_gene_table)
master_gene_table$ensembl <- rownames(HumDev_reference)
idx =which(is.na(master_gene_table$master_gene_table))
master_gene_table$master_gene_table[idx]<- master_gene_table$ensembl[idx]

genesymbsort <- master_gene_table[rownames(HumDev_reference), "master_gene_table"]
genesymbsort <- make.names(genesymbsort,  unique =  T, allow_ = T)
# length(unique(genesymbsort))==length(genesymbsort)
rownames(HumDev_reference) <- genesymbsort

HumDev_reference <- subset(HumDev_reference, cells = WhichCells(HumDev_reference, downsample = 200))

gc()
HumDev_reference <-   NormalizeData(HumDev_reference) 
HumDev_reference <-   ScaleData(HumDev_reference) 
HumDev_reference <-   FindVariableFeatures(HumDev_reference)
HumDev_reference <-   RunPCA(HumDev_reference) 
HumDev_reference <-   RunUMAP(HumDev_reference, reduction = "pca", dims = 1:30)
HumDev_reference <-   FindNeighbors(HumDev_reference, dims = 1:30, reduction = "pca")
HumDev_reference <-   FindClusters(HumDev_reference)
gc()
```

```{r maphumdev plot humdev ref cluster, fig.width=6, fig.height=8}
p<- DimPlot(HumDev_reference, group.by = "humdev_celltype")+
  theme(legend.position = c("bottom"),
        legend.justification = c("right", "top"),
        legend.text = element_text(size=3), 
        legend.key.size = unit(0.5,"line"))
p
```


```{r maphumdev predict}
AR<- as.SingleCellExperiment(HumDev_reference)
pred.cellclass<-SingleR(test = scRNA.sce,ref = AR,labels = AR$humdev_celltype)

colnames(pred.cellclass) <- paste0("Hum_dev.", colnames(pred.cellclass))
seurat_integrated@meta.data <- cbind(seurat_integrated@meta.data, pred.cellclass)

seurat_integrated@meta.data <- cbind(seurat_integrated@meta.data, Hum_dev.hsapDv=substr(pred.cellclass$Hum_dev.labels, 1,14), Hum_dev.Celltype=gsub("\'", "", substr(pred.cellclass$Hum_dev.labels, 17,100)))

labelcounts <- unlist(table(pred.cellclass$Hum_dev.labels))
setNA = names(labelcounts)[labelcounts<30]

cleanedlab = pred.cellclass$Hum_dev.labels 
cleanedlab[cleanedlab %in% setNA] = "other"

seurat_integrated@meta.data <- cbind(seurat_integrated@meta.data, Hum_dev.labels.main = cleanedlab)
seurat_integrated@meta.data <- cbind(seurat_integrated@meta.data, Hum_dev.labels.CtDv = paste0(seurat_integrated$Hum_dev.Celltype, "_", seurat_integrated$Hum_dev.hsapDv))

cleanedlab = seurat_integrated$Hum_dev.labels.CtDv
labelcounts <- unlist(table(cleanedlab))
setNA = names(labelcounts)[labelcounts<30]
cleanedlab[cleanedlab %in% setNA] = "other"
seurat_integrated@meta.data <- cbind(seurat_integrated@meta.data, Hum_dev.labels.CtDv.main = cleanedlab)

cleanedlab = seurat_integrated$Hum_dev.Celltype
labelcounts <- unlist(table(cleanedlab))
setNA = names(labelcounts)[labelcounts<30]
cleanedlab[cleanedlab %in% setNA] = "other"
seurat_integrated@meta.data <- cbind(seurat_integrated@meta.data, Hum_dev.Celltype.main = cleanedlab)

```

```{r maphumdevplot details, fig.width=18, fig.height=6}
p<- DimPlot(seurat_integrated, group.by = "Hum_dev.labels.CtDv.main", label = T)

p2<- DimPlot(seurat_integrated, group.by = "seurat_clusters", label = T)

p|p2
ggsave("./output/02_Clustering/Clustering_Hum_devFullDetailsMapped.svg",p|p2)

```


```{r, fig.width=15, fig.height=8}
p<- DimPlot(seurat_integrated, group.by = "Hum_dev.hsapDv", label = T)
p2<- DimPlot(seurat_integrated, group.by = "Hum_dev.Celltype.main", label = T)
p|p2
ggsave("./output/02_Clustering/Clustering_Hum_devCellDevTypeMapped.svg",p|p2)
```


```{r maphumdev plot counts, fig.width=8, fig.height=6}
tabcelltype<-table(seurat_integrated$seurat_clusters, seurat_integrated$Hum_dev.labels.CtDv.main)

longcelltype<-melt(tabcelltype)
colnames(longcelltype) <-c("Cluster", "Celltype", "Count")

p <- ggplot(longcelltype, aes(x=Celltype, y=Cluster, size=Count))+geom_point()+
  theme_classic()+theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
p
ggsave("./output/02_Clustering/Clustering_Hum_devCellDevTypeClusterCounts.svg",p)
```


```{r maphumdev plot bars, fig.width=12, fig.height=6}
p <- ggplot(longcelltype, aes(fill=Celltype, x=Cluster, y=Count))+geom_bar(position="stack", stat="identity")+
  theme_classic()+theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

p2 <- ggplot(longcelltype, aes(fill=Celltype, x=Cluster, y=Count))+geom_bar(position="fill", stat="identity")+
  theme_classic()+theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

pcom = ggarrange(p, p2, common.legend = T, legend = "right")
pcom

ggsave("./output/02_Clustering/Clustering_Hum_devCellDevTypeClusterCountsBarplot.svg",pcom)
```

```{r plot all scores, fig.width=15, fig.height=10}

feats=grep("Hum_dev.scores", colnames(seurat_integrated@meta.data),value=T) 
p<-FeaturePlot(seurat_integrated, features = feats, keep.scale = "all", combine=F, order = T)
for(i in 1:length(feats)){
  p[[i]] <-p[[i]] + ggtitle(gsub("Hum_dev.scores.", "", feats[i]))
  ggsave(paste0("./output/02_Clustering/Clustering_Hum_devScore_",feats[i],".svg"), p[[i]])
}

ggarrange(plotlist=p, nrow = 4,ncol=4, common.legend = T, legend = "right")

```



```{r last cleanup}
# cleanup 
rm(list=ls()[!ls()%in%c("scRNA.sce", "seurat_integrated", "SamplePalette")])
gc()

```

```{r save}
saveRDS(seurat_integrated, file="./data/QC_dataClustered.filtTyped.rds")
```
